README.md
sample code places a file. The notes say it installs a package with YUM.
Correcting the notes.
=> Make notes match sample code

docs/index.xml, docs/resources/file-content/index.html, docs/resources/index.xml, docs/resources/module/index.html, docs/resources/param/index.html, docs/resources/user-group/index.html, docs/sitemap.xml, docs_source/content/resources/param.md, load/resource_test.go, render/render_test.go, resource/param/param.go, resource/param/preparer.go, resource/param/preparer_test.go
=> param: accept boolean values

.codeclimate.yml, blackbox/test_apply.sh, blackbox/test_apply_remote.sh, blackbox/test_apply_sourcefile.sh, blackbox/test_apply_sourcefile_remote.sh, blackbox/test_graph_dependencies.sh, blackbox/test_graph_generation.sh, blackbox/test_module_verify.sh, blackbox/test_required_param.sh, blackbox/test_self_serve.sh, prettyprinters/graphviz/graphviz_test.go, resource/user/user_test.go
Ignore some things, fix others. I'm leaving test name errors alone for now.
=> Fix climate issues

docs/index.xml, docs/resource-authors-guide/index.html, docs/resources/index.xml, docs/resources/param/index.html, docs/resources/user-group/index.html, docs/resources/user-user/index.html, docs/sitemap.xml, docs_source/content/resources/user.group.md, resource/group/group.go, resource/group/group_linux.go, resource/group/group_test.go, resource/group/preparer.go, resource/group/preparer_test.go, samples/group.hcl
- Allow adding and deleting a group without supplying `gid`
- Update docs to indicate `state` default if not provided
=> Fix/user group - Allow adding/deleting without gid

render/preprocessor/preprocessor.go
=> preproc: don't add fields for non-struct anon field

render/preprocessor/preprocessor.go
=> use thread-safe field cache

examples/docker-swarm-mode/main.tf, examples/elk/Vagrantfile, examples/elk/main.tf, resource/docker/container/container.go, resource/docker/image/image.go
=> Fixes docker resources and updates examples

.codeclimate.yml, CHANGELOG.md
Keep track of changes in this PR
=> update for PR #307

.codeclimate.yml
=> fix codeclimate yaml

apply/apply_test.go, apply/pipeline.go, plan/pipeline.go, resource/shell/shell.go, resource/status.go, resource/status_test.go
Improves error handling.
Fixes #243 
Required for #331 
~~Doesn't do documentation because it would conflict with #321 so that needs to maybe go in first?~~
=> Status Error Codes

docs_source/content/resource-authors-guide.md, resource/preparer.go, resource/preparer_test.go
=> Ability to use pointers as a preparer value

docs_source/content/resources/docker.container.md, docs_source/content/resources/docker.image.md, docs_source/content/resources/file.content.md, docs_source/content/resources/file.directory.md, docs_source/content/resources/file.mode.md, docs_source/content/resources/module.md, docs_source/content/resources/param.md, docs_source/content/resources/task.md, docs_source/content/resources/task.query.md, docs_source/content/resources/user.group.md, docs_source/content/resources/user.user.md, resource/group/group.go, resource/group/group_default.go, resource/group/group_linux.go, resource/group/group_test.go, resource/group/preparer.go, resource/group/preparer_test.go
- Ability to modify a group name and/or gid
=> Support for modifying linux groups

helpers/comparison/diff.go, helpers/comparsion/diff.go, resource/docker/container/container_test.go
Refactor common stuff from container_test.
(I use it in lvm/*/*_test.go also)
=> helpers,docker: move AssertDiff to common testhelpers

resource/wait/port/port.go, resource/wait/port/port_test.go, resource/wait/retrier.go, resource/wait/retrier_test.go
=> wait: fix error handling in retrier

.codeclimate.yml
=> codeclimate: remove markdown linting

cmd/server.go
=> cmd/server.go: use errgroup instead of waitgroup

resource/group/group.go
Update group to use status.RaiseLevel() instead of stetting status.Level
=> Use status.RaiseLevel in group

resource/packages/rpm/preparer.go, samples/rpm.hcl
=> Change `rpm.package` to `package.rpm`

load/dependencyresolver.go, samples/moduleDep.hcl
=> don't exclude modules in getNearestAncestor

Makefile, examples/elk/converge/docker.hcl, resource/docker/container/container.go, resource/docker/container/container_test.go
=> Fix container entrypoint diffs

wercker.yml
It's deleting stuff when it doesn't need to. This should fix it.
=> wercker: don't delete removed

README.md, install-converge.sh
Add installation script. 
Script determines OS and cpu type to download the correct release.
=> add installation script

transform/control.go
in reference to [issue #389](https://github.com/asteris-llc/converge/issues/389)
=> [389] switch log level from Info to Debug

docs/content/release-notes/0.3.0.md
include section on install scripts
=> update release notes

cmd/apply.go
=> return non-zero exit code if apply graph has an error

graph/graph.go, graph/graph_test.go, load/dependencyresolver.go
=> grouping: fix issues with groups and conditionals

ci/Dockerfile, wercker.yml
This generates manifests that can be parsed and displayed using [converge-dl](https://github.com/asteris-llc/converge-dl). I've already set up [the downloads page](http://converge-builds-dl.s3-website-us-east-1.amazonaws.com) using that code, this just will keep it updated automatically.
=> Manifest / index page

helpers/logging/formatter.go, helpers/logging/formatter_test.go
=> Use %v for logging

docs/content/release-notes/0.4.0.md
don't merge until we're ready to release
=> release notes

cmd/plan.go
=> plan cmd: return non-zero exit code when plan has error(s)

glide.lock, vendor/github.com/fsouza/go-dockerclient/client.go, vendor/github.com/fsouza/go-dockerclient/client_test.go, vendor/github.com/fsouza/go-dockerclient/network.go, vendor/github.com/fsouza/go-dockerclient/testing/server.go, vendor/github.com/fsouza/go-dockerclient/testing/server_test.go, vendor/github.com/fsouza/go-dockerclient/testing/swarm.go, vendor/github.com/fsouza/go-dockerclient/testing/swarm_test.go
fixes #485 
see https://github.com/fsouza/go-dockerclient/issues/605
=> docker: update docker dependency

cmd/graph.go
=> graph cmd: fix wrong argument length error

resource/preparer.go, resource/preparer_test.go
Adds handling of time.Time to the preparer.
Addresses #490
=> Feature/preparer time.time

examples/kubernetes/Vagrantfile, examples/kubernetes/terraform/aws/main.tf, examples/kubernetes/terraform/aws/variables.tf
=> demo: kubernetes - use latest version of converge

parse/node.go, parse/node_test.go, samples/conditionalDeps.hcl, samples/healthcheck.hcl, samples/query.hcl, samples/shellOutput.hcl
=> disallow some characters as resource names

resource/docker/network/network.go, resource/docker/network/network_test.go
=> return a better error for planned network failures

resource/lvm/fs/fs.go, resource/lvm/lowlevel/systemd.go
This doesn't have unit tests because of the complexity of the existing test mock infrastructure, but is covered by the lvm sample.
=> reset updates needed after apply in lvm

Makefile, render/factory.go, resource/docker/container/container.go, resource/docker/network/network.go, resource/docker/volume/volume.go, resource/file/fetch/fetch.go, resource/lvm/lowlevel/size.go, resource/wait/retrier.go, resource/wait/wait_test.go
This fixes all the outstanding linting bugs, except those in aligncheck (which I've removed; it wasn't getting us much benefit.)
=> Fix Linting Bugs

CHANGELOG.md, docs/content/release-notes/0.5.0.md
don't merge this, it will be a release merge.
=> no merge: update changelog

glide.lock, install-converge.sh
This updates the install script to install 0.5.0
=> Update installer to 0.5.0

resource/user/user.go, resource/user/user_test.go
Implements #444 
`<default home>` is no longer used for `create_home` or `skel_dir` diffs when adding a user.
Now, after a user is added, the actual home directory value is used for these diffs.
=> use home_dir value for user add diffs

load/dependencyresolver.go
Adding dependencies of group nodes to the group can cause cycles.
Build fails now but it shouldn't after a42283fa0496ca271753b11b20b70858b7999d7a (contained in #571)
=> load: remove addGroupDependenciesToGroup

docs/config.yaml, docs/content/extra.md, docs/content/extra/systemd-properties/automount_properties.md, docs/content/extra/systemd-properties/device_properties.md, docs/content/extra/systemd-properties/mount_properties.md, docs/content/extra/systemd-properties/path_properties.md, docs/content/extra/systemd-properties/properties.md, docs/content/extra/systemd-properties/scope_properties.md, docs/content/extra/systemd-properties/service_properties.md, docs/content/extra/systemd-properties/slice_properties.md, docs/content/extra/systemd-properties/socket_properties.md, docs/content/extra/systemd-properties/swap_properties.md, docs/content/extra/systemd-properties/timer_properties.md, docs/content/resources/systemd.unit.state.md
- publish docs for 0.6.0
- temp fix for extras for systemd properties
=> docs: update to 0.6.0, temp fix for extras

ci/Dockerfile
=> Update to build and test using Go 1.8

README.md, docs/content/commands.md, docs/content/configuration.md, docs/content/dependencies.md, docs/content/getting-started.md, docs/content/index.md, docs/content/resource-authors-guide.md, docs/content/resources.md, docs/content/server.md
Docs changes based on user feedback
=> docs: highlight resource reference, minor edits

install-converge.sh
This also removes some smells there and here like needless two step
checks for command status. However there is still much room to for
improvements.
=> Be sure that script is fully downloaded before run

ci/Dockerfile
Update golang and protoc versions.
=> Feature/golang 1.10
