load/dependencyresolver.go
render/extensions/extensions.go

unimplemented calls result in early template execution termination.
Fixes issue #254

Use `MakeLanguage` for dependecy resolution to ensure that no

---

cmd/apply.go
cmd/healthcheck.go
cmd/plan.go
cmd/validate.go
docs/getting-started/index.html
docs_source/content/getting-started.md
load/dependencyresolver.go
load/resource.go
resource/shell/preparer.go
rpc/executor.go
rpc/grapher.go
rpc/resourcehost.go

Make the logs quieter

---

cmd/rpc.go
cmd/server.go

cmd: don't set local token if only a client

---

docs/index.xml
docs/resources/file-directory/index.html
docs/resources/index.xml
docs/resources/param/index.html
docs/resources/user-group/index.html
docs/resources/user-user/index.html
docs/sitemap.xml
docs_source/content/resources/user.user.md
resource/user/preparer.go
resource/user/preparer_test.go
resource/user/user.go
resource/user/user_default.go
resource/user/user_linux.go
resource/user/user_test.go

Can now add a user by specifying either the group name or gid.

Add ability to indicate the group name when adding a user

---

parse/node.go
parse/node_test.go

map keys are considered "strings" in parse.Node

---

resource/shell/shell.go
resource/shell/shell_test.go

shell: non-0 exit code returns StatusWillChange

---

resource/file/mode/mode.go
resource/file/mode/mode_test.go
resource/file/mode/preparer.go
resource/file/mode/preparer_test.go
resource/group/preparer.go
resource/group/preparer_test.go
resource/user/preparer.go
resource/user/preparer_test.go

Uses #339 to handle module parameters in which zero is a valid value.
Updated the following modules:
- file.mode
- user.group
- user.user

Handle preparer fields where zero is valid

---

apply/pipeline.go
resource/docker/container/container.go
resource/docker/container/preparer.go
resource/docker/container/preparer_test.go

fixes #343 
also brings back the docker-related validations that were removed in #321 (see #337)

Fix docker regressions

---

docs_source/content/resource-authors-guide.md

docs: add section on error values to resource author's guide

---

CHANGELOG.md
docs/index.xml
docs/resources/index.xml
docs/resources/task/index.html
docs_source/content/resources/task.md
docs_source/content/resources/wait.port.md
docs_source/content/resources/wait.query.md
docs_source/sources.csv
examples/elk/Vagrantfile
examples/elk/converge/elk.hcl
load/resource.go
resource/shell/preparer.go
resource/wait/port/port.go
resource/wait/port/port_test.go
resource/wait/port/preparer.go
resource/wait/port/preparer_test.go
resource/wait/preparer.go
resource/wait/preparer_test.go
resource/wait/retrier.go
resource/wait/retrier_test.go
resource/wait/wait.go
resource/wait/wait_test.go
samples/wait.hcl
samples/waitPort.hcl

wait.query and wait.port resources

---

docs_source/content/params-and-templates.md
glide.lock
glide.yaml
load/dependencyresolver.go
render/extensions/defaults.go
render/extensions/extensions.go
render/extensions/extensions_test.go
render/renderer.go
resource/preparer.go
samples/customInterpreter.hcl
samples/docker.hcl
samples/paramJoin.hcl
samples/paramJsonify.hcl
samples/paramList.hcl
samples/paramMap.hcl
vendor/github.com/arbovm/levenshtein/LICENSE
vendor/github.com/arbovm/levenshtein/levenshtein.go
vendor/github.com/arbovm/levenshtein/levenshtein_test.go

See examples for more.
Fixes #110

Add Compound Parameters

---

prettyprinters/human/human.go
prettyprinters/human/human_test.go

This commit adds the text/tabwriter package to the human prettyprinter
package, and updates test case inputs. This aligns values based on a new
tab inserted to the right of the colon.
Fixes #244

Use text/tabwriter to align human output

---

CONTRIBUTING.md

Add information on testing and including it when contributing.

Add testing section to contribution guidelines

---

docs_source/content/getting-started.md

As discussed in Slack, just a simple fix in the getting started page. The user is running locally, so you need the `--local` flag in the example command, just like all the others are on the page, to allow it to run without error.
```
- Now try running `converge plan helloYou.hcl`. The same thing happens as if you had called the module yourself!
+ Now try running `converge plan --local helloYou.hcl`. The same thing happens as if you had called the module yourself!
```

FIX local command flag added to example

---

README.md
ci/Dockerfile
docs_source/content/index.md
wercker.yml

We had a bunch of dependencies we were installing before CI would begin. No need to do those all the time. Let's just use a custom container. Thanks Wercker!

use a container for CI

---

resource/user/user.go
resource/user/user_test.go

- Updates status level and errors for user
- Adds checks in Apply() when adding a user with a group
- Verifies that the group name or gid exists prior to adding
- Returns useful error if the group does not exist

Update user status level and errors, add checks in Apply for group

---

resource/user/user.go

Was using the system specific implementation (SystemUtils) for Group and GroupId lookups; this caused issues in testing with systems that have not been implemented for user. 
Changed the calls in SetAddUserOptions() to use os/user lookups for Group and GroupId.

Fix lookup calls to use os/user in SetAddUserOptions

---

docs/content/getting-started.md

There are several known issues with conditionals that have been identified.  This updates the documentation to explicitly call out things that are unlikely to get merged for 0.3.0

update docs to include currently identified switch statement limitations

---

helpers/fakerenderer/fakerenderer.go
parse/preprocessor/switch/control_test.go
render/factory.go
render/render.go
render/renderer.go
resource/module/module.go
resource/module/preparer.go
resource/resource.go
samples/sourceFileParamJoin.hcl

This allows literal lists in parameters when calling a module.
Fixes #397

Allow lists in parameters when called in a module

---

cmd/version.go
docs/content/release-notes.md
docs/content/release-notes/0.2.0.md
docs/content/release-notes/0.3.0.md

Before 0.3.0 release tag:
- update release notes and changelog
- update `cmd/version.go`

0.3.0 release documentation

---

.gitignore
Makefile
cmd/version.go

The current version that creates a .go file interferes with `go get` on our repository. 
This version uses ldflags at build time, and will display `unset` if converge is built outside of
the make process.

 use ldflags to set version

---

Makefile

Add hashes to files. This ends with a directory structure like:
```
build
├── converge_0.3.0-rc1_darwin_386
│   ├── converge
│   └── converge.sha256sum
├── converge_0.3.0-rc1_darwin_amd64
│   ├── converge
│   └── converge.sha256sum
├── converge_0.3.0-rc1_freebsd_386
│   ├── converge
│   └── converge.sha256sum
├── converge_0.3.0-rc1_freebsd_amd64
│   ├── converge
│   └── converge.sha256sum
├── converge_0.3.0-rc1_freebsd_arm
│   ├── converge
│   └── converge.sha256sum
├── converge_0.3.0-rc1_linux_386
│   ├── converge
│   └── converge.sha256sum
├── converge_0.3.0-rc1_linux_amd64
│   ├── converge
│   └── converge.sha256sum
├── converge_0.3.0-rc1_linux_arm
│   ├── converge
│   └── converge.sha256sum
├── converge_0.3.0-rc1_linux_arm64
│   ├── converge
│   └── converge.sha256sum
├── …
```

makefile: add hashes to files

---

docs/content/resources/user.group.md
docs/content/resources/user.user.md
resource/group/preparer.go
resource/user/preparer.go
resource/user/preparer_test.go
resource/user/user.go
resource/user/user_default.go
resource/user/user_linux.go
resource/user/user_test.go

Add the ability to modify a user #278 
Fixes #425

Add the ability to modify a user

---

resource/package/rpm/preparer.go
resource/package/rpm/preparer_test.go

ensure rpm checks for an empty package name

check rpm for empty packages

---

docs/content/resources/docker.container.md
docs/content/resources/docker.network.md
docs/sources.csv
load/resource.go
resource/docker/container/container.go
resource/docker/container/container_test.go
resource/docker/container/preparer.go
resource/docker/docker.go
resource/docker/image/image_test.go
resource/docker/network/network.go
resource/docker/network/network_test.go
resource/docker/network/preparer.go
resource/docker/network/preparer_test.go
samples/docker.hcl
samples/dockerContainer.hcl
samples/dockerNetwork.hcl

docker.network resource

---

docs/content/license.md
docs/content/resource-authors-guide.md
docs/content/resources/docker.container.md
docs/content/resources/docker.image.md
docs/content/resources/docker.network.md
docs/content/resources/docker.volume.md
docs/content/resources/file.content.md
docs/content/resources/file.directory.md
docs/content/resources/file.mode.md
docs/content/resources/module.md
docs/content/resources/package.rpm.md
docs/content/resources/param.md
docs/content/resources/task.md
docs/content/resources/task.query.md
docs/content/resources/user.group.md
docs/content/resources/user.user.md
docs/content/resources/wait.port.md
docs/content/resources/wait.query.md
docs/extract.go
resource/docker/image/preparer.go
resource/docker/image/preparer_test.go
resource/preparer.go
resource/preparer_test.go
resource/shell/preparer.go
resource/shell/query/preparer.go
resource/wait/port/preparer.go
resource/wait/preparer.go
resource/wait/retrier.go
resource/wait/retrier_test.go

- Add time.Duration to resource/preparer, giving the ability to provide a duration as a number in nanoseconds or as a duration string.
- Updated the preparer for docker image, shell, and wait resources
- Added handling to documentation generation for time.Duration
- Moved duplicate comments regarding duration strings (from each of the preparers for docker image, shell, and wait resources) to be handled by docs generation

Feature/preparer time.duration

---

cmd/apply.go
cmd/plan.go
cmd/timerdisplay.go
cmd/util.go
cmd/util_test.go
glide.lock
glide.yaml
vendor/github.com/gosuri/uilive/LICENSE
vendor/github.com/gosuri/uilive/doc.go
vendor/github.com/gosuri/uilive/example/main.go
vendor/github.com/gosuri/uilive/example_test.go
vendor/github.com/gosuri/uilive/writer.go
vendor/github.com/gosuri/uilive/writer_posix.go
vendor/github.com/gosuri/uilive/writer_test.go
vendor/github.com/gosuri/uilive/writer_windows.go

This adds an incremental status display for long-running tasks.
Fixes #269

Timer status display

---

docs/content/resources/docker.container.md
docs/content/resources/docker.image.md
docs/content/resources/docker.network.md
docs/content/resources/docker.volume.md
docs/content/resources/file.content.md
docs/content/resources/file.directory.md
docs/content/resources/file.fetch.md
docs/content/resources/file.mode.md
docs/content/resources/filesystem.md
docs/content/resources/lvm.logicalvolume.md
docs/content/resources/lvm.volumegroup.md
docs/content/resources/module.md
docs/content/resources/package.apt.md
docs/content/resources/package.rpm.md
docs/content/resources/param.md
docs/content/resources/task.md
docs/content/resources/task.query.md
docs/content/resources/user.group.md
docs/content/resources/user.user.md
docs/content/resources/wait.port.md
docs/content/resources/wait.query.md
docs/extract.go

Add a newline after the name and type for exported and re-exported fields.
Fixes #548

docs: use same formatting for (re)exported fields as parameters

---

Makefile
cmd/version.go

Fixes syntax errors, missing variables, and enforces a set version for `converge version`.

Minor Fixes After Makefile rewrite

---

docs/content/resources/docker.container.md
docs/content/resources/docker.image.md
docs/content/resources/docker.network.md
docs/content/resources/docker.volume.md
docs/content/resources/file.content.md
docs/content/resources/file.directory.md
docs/content/resources/file.fetch.md
docs/content/resources/file.mode.md
docs/content/resources/file.owner.md
docs/content/resources/filesystem.md
docs/content/resources/lvm.logicalvolume.md
docs/content/resources/lvm.volumegroup.md
docs/content/resources/module.md
docs/content/resources/package.apt.md
docs/content/resources/package.rpm.md
docs/content/resources/param.md
docs/content/resources/task.md
docs/content/resources/task.query.md
docs/content/resources/user.group.md
docs/content/resources/user.user.md
docs/content/resources/wait.port.md
docs/content/resources/wait.query.md
docs/extract.go

Add checks to only include params and exported fields in the docs if they are exported(public).

docs: only list exported fields in param and export sections

---

docs/content/resource-authors-guide.md
resource/docker/container/container.go
resource/docker/image/image.go
resource/docker/network/network.go
resource/docker/volume/volume.go
resource/file/fetch/fetch.go
resource/group/group.go
resource/lvm/fs/fs.go
resource/lvm/vg/vg.go
resource/status.go
resource/user/user.go

A new method on status `RaiseLevelForDiffs` checks if there are any diffs and raises the level to `StatusWillChange`.
Resources were updated to call this new method in the following cases:
- The same check was being performed prior to raising the level to `StatusWillChange`
- Multiple calls to `AddDifference`/`RaiseLevel` to `StatusWillChange`: the calls to `RaiseLevel` were removed and a call to this new method was added at the end of the function.
Implements #586

add status method-raise level to will change when there are diffs

---

wercker.yml

This PR will set up wercker to upload the installer to the `get.converge.sh` s3 bucket for the static website.

have wercker install script on get.converge.sh

---

examples/docker-swarm-mode/converge/awscli.hcl

the docker swarm example fails due to a name change in the python-pip package.

update pip package to fix failing example

---

blackbox/test_graph_generation.sh

There wasn't any sleeping in the graph generation test. I'm not sure why it didn't give us problems before, but it is now. This PR adds a quarter second sleep between starting the server and using it.

Sleep in Graph Generation Test

---

Makefile

The binaries are too big, this shrinks them down again. These are the flags we ship Converge with, so we should build local test binaries with them too.

Makefile: restore -s -w to converge target
